### ISSUE TITLE
Number of channels for mask for binary segmentation

### ISSUE THREAD

**Issue by PeterMcGor** [nv-tlabs/semanticGAN_code#11]
Hi, 
Thanks for releasing the code!
Just a silly question: 
I have no experience with GANs and the loss functions employed so I was wondering if the optimization process works better when binary masks are given in two channels or just with one  (0:background, 1:Region of interest). For example for the X-Ray problem, how do you feed the model? 

Thank you!

**Comment by zeta7337** [comment]
> Hi, Thanks for releasing the code! Just a silly question: I have no experience with GANs and the loss functions employed so I was wondering if the optimization process works better when binary masks are given in two channels or just with one (0:background, 1:Region of interest). For example for the X-Ray problem, how do you feed the model?
> 
> Thank you!

same question,have you fixed it?

**Comment by PeterMcGor** [comment]
I tried both and I got slightly better FID scores (same initialization) with two channels but I haven't tried a proper evaluation on the subject. Some operations are more numerically stable employing two channels but in this case, I haven't checked in detail. 

Let me know how it works for you!

**Comment by lidaiqing** [comment]
Hi @PeterMcGor , no problem at all and sorry for the late reply. If you have a region of interest, you can apply a mask when doing inverse optimization where only the region of interest is reconstructed/segmented. In this case, depends on your use case, you might want to evaluate it by the task performance.
