### ISSUE TITLE
There is no softmax in the forward function of GeneratorSeg

### ISSUE THREAD

**Issue by sangyun884** [nv-tlabs/semanticGAN_code#12]
There is no softmax in the forward function of GeneratorSeg, and the output segmentation map of the generator is directly fed to the discriminator. How does a generator fool a discriminator if the output segmentation map is not normalized?

**Comment by lidaiqing** [comment]
Hi, sorry for the late reply. It is the same as the image generation branch where there is also no tanh layer. Stylegan is well normalized in each layer, but you can also try using normalization layer before the output.
