### ISSUE TITLE
Can I use pre-trained StyleGAN model and finetune just the segmentation branch?

### ISSUE THREAD

**Issue by tommy-qichang** [nv-tlabs/semanticGAN_code#14]
Hi, thank you for your great work.
I just wondering if we already have a well-trained stylegan2 model(without the segmentation branch) can we finetune with your architecture?

**Comment by lidaiqing** [comment]
Hi thank you for your interest on our work. Yes if you just fine-tune the segmentation branch, it will be similar to another work from our lab DatasetGAN https://github.com/nv-tlabs/datasetGAN_release.
