### ISSUE TITLE
Can't load encoder checkpoints return KeyError: 'e'

### ISSUE THREAD

**Issue by besawe** [nv-tlabs/semanticGAN_code#22]
When I set mean_init == False to load the encoder checkpoints it returns a KeyError for not finding the checkpoints for the FPNEncoder. Isn't the encoder weights already part of the saved checkpoint during training?

**Comment by besawe** [comment]
I should have trained a separate encoder to predict on input images instead of latent noise

**Comment by vunh** [comment]
@besawe could you please clarify how you fix this problem? 

Thank you in advance.

**Comment by besawe** [comment]
@vunh For semanticGAN, there are two steps to follow. First, you need to run train_seg_gan.py script to train a segmentation gan model which learns to generate images and masks. However, the generated images are generated from latent noise. This means if you tried to load this model for testing, it will generate images and masks from noise. In order to get a segmentation model that can predict on actual images of your choice, you have to follow step two which is using the checkpoint from step one to train a new model that can predict on actual images. This can be done by running the script "train_enc.py" and pass in for the argument "ckpt" the checkpoint generated from running train_seg_gan.py. If your tried to run the inference using the checkpoint from step one (train_seg_gan.py) then you will get this error because there are no encoder weights in this checkpoint. I hope my explanation is clear
