### ISSUE TITLE
train_enc.py: ValueError: Target size (torch.Size([1, 1, 512, 512])) must be the same as input size (torch.Size([4, 1, 512, 512]))

### ISSUE THREAD

**Issue by besawe** [nv-tlabs/semanticGAN_code#27]
Somehow I am getting the input batch size multiplied by 4 compared to the target batch size. Btw, I am using my own custom dataset instead of CelebaDataset

**Comment by lww28** [comment]
Hi, @besawe how did you solve this problem? I am facing the same issue. Appreciate if you can help.
