### ISSUE TITLE
Dataset organization issues

### ISSUE THREAD

**Issue by Sinjini15** [nv-tlabs/semanticGAN_code#31]
When trying to run the `prepare_inception.py` script, I am getting the following error:

`OSError: ./semanticGAN_code/CelebAMask-HQ/CelebA-HQ-img/unlabel_data/unlabel_list.txt not found.`

It seems like the `unlabel_data` directory does not exist within the CelebA Mask dataset. How can I find the missing file and organize the directory?

**Comment by lidaiqing** [comment]
hi @Sinjini15 , prepare_inception.py is trying to calculate FID stats on real images and store it locally. You can generate the list of image in `unlabel_list.txt` or modify data loader on how to load the images.
