### ISSUE TITLE
Where is the dataset?

### ISSUE THREAD

**Issue by BorHon** [nv-tlabs/semanticGAN_code#6]
Hi! Thank you so much for sharing!

I want to reproduce the paper but I can't find a website for downloading your dateset. Could you please tell me how to
collect the training data? Thanks in advance.

**Comment by lidaiqing** [comment]
Hi there, which dataset are you looking for? If you are looking for face dataset, we were using CelebA-HQ dataset, you can find it here https://github.com/switchablenorms/CelebAMask-HQ
