### ISSUE TITLE
Is annotated MetFaces available? 

### ISSUE THREAD

**Issue by yangyu12** [nv-tlabs/semanticGAN_code#8]
Hi, thanks for releasing the source code. I am wondering if there is any plan to make the annotated MetFaces public? As in the paper, 40 images are selected from MetFaces and manually annotated for out-of-domain evaluation. I want to do a similar evaluation for our methods. It would be a huge help if this dataset were made public. Thanks a lot!

**Comment by vunh** [comment]
Hi @lidaiqing,

Could you please release the names of images in the MetFaces dataset that you labeled?

**Comment by lidaiqing** [comment]
we just release the MetFaces40 dataset, please see the readme and here https://drive.google.com/drive/folders/1ibZzaWSUVoQ94OPoLNS0FrUufBeDvRP4?usp=sharing
