### ISSUE TITLE
[Help] I encountered a problem when running the code

### ISSUE THREAD

**Issue by bofen97** [nv-tlabs/semanticGAN_code#9]
![1501631270846_ pic_hd](https://user-images.githubusercontent.com/42445931/132843253-0363ea1f-55fb-435c-a8ce-273f86f66e2f.jpg)

I think it was unsuccessful when the operators were fused.

**Comment by lidaiqing** [comment]
Hi, we test our code on Linux environment. It seems like you need to do some configuration to build extension in windows envionment see rosinality/stylegan2-pytorch#47
